---

- name: Include user creation tasks
  ansible.builtin.include_tasks: user.yml
  when: slurm_create_user
 
- name: Include Configure custom repositories
  ansible.builtin.include_tasks: repositories-Debian.yml
  when: slurm_configure_repos

- name: Include controller installation tasks
  ansible.builtin.include_tasks: slurmctld.yml
  when: "'slurmservers' in group_names or 'controller' in slurm_roles"

- name: Include execution host installation tasks
  ansible.builtin.include_tasks: slurmd.yml
  when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"

- name: Include DB installation tasks
  ansible.builtin.include_tasks: slurmdbd.yml
  when: "'slurmdbdservers' in group_names or 'dbd' in slurm_roles"

- name: Import common tasks
  ansible.builtin.import_tasks: common.yml

- name: Ensure slurmdbd is enabled and running
  ansible.builtin.service:
    name: "{{ slurmdbd_service_name }}"
    enabled: true
    state: started
  when: "(slurm_start_services | bool) and ('slurmdbdservers' in group_names or 'dbd' in slurm_roles)"

- name: Ensure slurmctld is enabled and running
  ansible.builtin.service:
    name: "{{ slurmctld_service_name }}"
    enabled: true
    state: started
  when: "(slurm_start_services | bool) and ('slurmservers' in group_names or 'controller' in slurm_roles)"

- name: Ensure slurmd is enabled and running
  ansible.builtin.service:
    name: "{{ slurmd_service_name }}"
    enabled: true
    state: started
  when: "(slurm_start_services | bool) and ('slurmexechosts' in group_names or 'exec' in slurm_roles)"

- name: Setup cluster on slurmdb
  include_tasks: slurmdbd_cluster.yml
  when: "(slurm_start_services | bool) and ('slurmdbdservers' in group_names or 'dbd' in slurm_roles)"
