---

- name: Include user creation tasks
  include_tasks: user.yml
  when: slurm_create_user

- name: Include controller installation tasks
  include_tasks: slurmctld.yml
  when: "'slurmservers' in group_names or 'controller' in slurm_roles"

- name: Include execution host installation tasks
  include_tasks: slurmd.yml
  when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"

- name: Include DB installation tasks
  include_tasks: slurmdbd.yml
  when: "'slurmdbdservers' in group_names or 'dbd' in slurm_roles"

- name: Import common tasks
  import_tasks: common.yml

- name: Ensure slurmdbd is enabled and running
  service:
    name: "{{ slurmdbd_service_name }}"
    enabled: yes
    state: started
  when: "'slurmdbdservers' in group_names or 'dbd' in slurm_roles"

- name: Ensure slurmctld is enabled and running
  service:
    name: "{{ slurmctld_service_name }}"
    enabled: yes
    state: started
  when: "'slurmservers' in group_names or 'controller' in slurm_roles"

- name: Ensure slurmd is enabled and running
  service:
    name: "{{ slurmd_service_name }}"
    enabled: yes
    state: started
  when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"
