---

- name: Install Slurm execution host packages
  ansible.builtin.package:
    name: "{{ __slurm_packages.slurmd }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"

- name: Create slurm spool directory
  ansible.builtin.file:
    path: "{{ __slurm_config_merged.SlurmdSpoolDir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  when: slurm_create_dirs
  notify:
    - Reload slurmd

- name: Create slurm log directory
  ansible.builtin.file:
    path: "{{ __slurm_config_merged.SlurmdLogFile | dirname }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurm_config_merged.SlurmdLogFile != omit

- name: Include config dir creation tasks
  ansible.builtin.include_tasks: _inc_create_config_dir.yml
  when: slurm_create_dirs

- name: Include extra config creation tasks
  ansible.builtin.include_tasks: _inc_extra_configs.yml
