---

- name: Install Slurm DB packages
  package:
    name: "{{ __slurm_packages.slurmdbd }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"

- name: Install slurmdbd.conf
  template:
    src: generic.conf.j2
    dest: "{{ slurm_config_dir }}/slurmdbd.conf"
    owner: "{{ __slurm_user_name }}"
    group: root
    mode: 0400
  notify:
    - reload slurmdbd

- name: Create slurm log directory
  file:
    path: "{{ __slurmdbd_config_merged.LogFile | dirname }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurmdbd_config_merged.LogFile
